command = "docker"
default = "unknown"

[subcommands.ps]
default = "read"

[subcommands.images]
default = "read"

[subcommands.logs]
default = "read"

[subcommands.inspect]
default = "read"

[subcommands.build]
default = "write"

[subcommands.run]
default = "unknown"
recursive = true
separator = "--"

[subcommands.exec]
default = "unknown"
recursive = true
separator = "--"

[subcommands.pull]
default = "write"

[subcommands.push]
default = "write"

[subcommands.rm]
default = "write"

[subcommands.rmi]
default = "write"

[subcommands.stop]
default = "write"

[subcommands.start]
default = "write"
