command = "go"
default = "unknown"

[subcommands.version]
default = "safe"

[subcommands.build]
default = "safe"

[subcommands.test]
default = "safe"

[subcommands.run]
default = "unknown"

[subcommands.mod]
default = "write"

[subcommands.get]
default = "write"

[subcommands.vet]
default = "safe"

[subcommands.fmt]
default = "write"

[subcommands.doc]
default = "safe"

[subcommands.tool]
default = "safe"
