command = "npm"
default = "unknown"

[subcommands.list]
default = "safe"

[subcommands.ls]
default = "safe"

[subcommands.install]
default = "write"

[subcommands.publish]
default = "write"

[subcommands.run]
default = "unknown"

[subcommands.test]
default = "safe"

[subcommands.version]
default = "safe"

[subcommands.init]
default = "write"

[subcommands.uninstall]
default = "write"
