command = "pip"
default = "unknown"

[subcommands.list]
default = "safe"

[subcommands.install]
default = "write"

[subcommands.uninstall]
default = "write"

[subcommands.show]
default = "safe"

[subcommands.freeze]
default = "safe"
